### ISSUE TITLE
Excel document is only 3382 line and shouw be 88000

### ISSUE THREAD

**Issue by damhau** [raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report#5]
Hi,

I'm running a query that shoud get approx 80'000 result but the excel file contain only 3382.
If I check the query directly on ES I get the right number of document.

Is there a limit in Elastictab ?

Cheers,

Damien

**Comment by damhau** [comment]
I've found out that lowering the batch.size settings in elastictab.properties to 10 get me more result.
I'll do some more testing and report back the results.

**Comment by raghavendar-ts** [comment]
There is no limit for the property batch.size. You also check the log for more info.

**Comment by damhau** [comment]
If I leave the batch.size to 250 i got 3382 line in the excel file and if I change it to 50 i got somehting like 22000 line in the excel file.
I ve tried with batch.size 10 but it is slow.
I ve alredy checked the log nothing there.

What is exactly doing batch.size ?

**Comment by raghavendar-ts** [comment]
If we have 2000 documents in Elasticsearch and say we have batch.size as 200, we will hit Elasticsearch in terms of batch. So here the number of hits from ElasticTab to Elasticsearch will be 10(2000/200=10). Can you post the log infomation which has the processed count info? Something similar to **Processed xyz of totalHits**

**Comment by damhau** [comment]
Hi,

Sorry for the delay I was not able to test.

So here is what I have in the log with the default settings (which seems to be 250):

Building Excel Report
Processed 250 of 12139
Processed 500 of 12139
Processed 750 of 12139
Processed 1000 of 12139
Processed 1250 of 12139
Processed 1500 of 12139
Processed 1750 of 12139
Processed 2000 of 12139
Processed 2250 of 12139
Processed 2500 of 12139
Processed 2750 of 12139
Processed 3000 of 12139
Processed 3250 of 12139
Processed 3500 of 12139
Processed 3750 of 12139
Processed 4000 of 12139
Processed 4250 of 12139
Processed 4500 of 12139
Processed 4750 of 12139
Processed 5000 of 12139
Processed 5250 of 12139
Processed 5500 of 12139
Processed 5750 of 12139
Processed 6000 of 12139
Processed 6250 of 12139
Processed 6500 of 12139
Processed 6750 of 12139
Processed 7000 of 12139
Processed 7250 of 12139
Processed 7500 of 12139
Processed 7750 of 12139
Processed 8000 of 12139
Processed 8250 of 12139
Processed 8500 of 12139
Processed 8750 of 12139
Processed 9000 of 12139
Processed 9250 of 12139
Processed 9500 of 12139
Processed 9750 of 12139
Processed 10000 of 12139
Processed 10250 of 0
Finished processing data

This ES query should output 12'369 results.

When I open the excel file I've only 400 lines.

Now if I change the batch.size to 10 here is the log:

Setting Title and Headers
Building Excel Report
Processed 10 of 12139
Processed 20 of 12139
Processed 30 of 12139
Processed 40 of 12139
Processed 50 of 12139
Processed 60 of 12139
... ommited ...
Processed 9830 of 12139
Processed 9840 of 12139
Processed 9850 of 12139
Processed 9860 of 12139
Processed 9870 of 12139
Processed 9880 of 12139
Processed 9890 of 12139
Processed 9900 of 12139
Processed 9910 of 12139
Processed 9920 of 12139
Processed 9930 of 12139
Processed 9940 of 12139
Processed 9950 of 12139
Processed 9960 of 12139
Processed 9970 of 12139
Processed 9980 of 12139
Processed 9990 of 12139
Processed 10000 of 12139
Processed 10010 of 0
Finished processing data

And now the excel has 10'000 lines (which is 25 \* 400) but the report is a lot slower.

Do you have any idea ? Or what else can I provide to help you troubleshoot this problem ?

If needed I would even pay you for support, one of my customer would really like to use you tools for their ES reporting.

Thanks.

Damien

**Comment by damhau** [comment]
Additional info, I've done some more test and I've got an error from ES sometimes:
HTTP ERROR 500

Problem accessing /API/esreport/download. Reason:

```
Server Error
```

Caused by:

Failed to execute phase [query], all shards failed; shardFailures {[gV2-Eh-DRsasw1warhWu3Q][cucm-cmr-08.2016][0]: RemoteTransportException[[chbsuv-naesdb01.it.actelion.com][10.180.147.47:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]; }{[B5F-dltaQFyeEk1xKVaYxA][cucm-cmr-08.2016][1]: RemoteTransportException[[chbsuv-naesdb02.it.actelion.com][10.180.148.45:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]; }{[gV2-Eh-DRsasw1warhWu3Q][cucm-cmr-08.2016][2]: RemoteTransportException[[chbsuv-naesdb01.it.actelion.com][10.180.147.47:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]; }{[8RNuqckiQz6WNF9ZpswwGw][cucm-cmr-08.2016][3]: RemoteTransportException[[chbsuv-naesdb03.it.actelion.com][10.180.148.48:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]; }{[B5F-dltaQFyeEk1xKVaYxA][cucm-cmr-08.2016][4]: RemoteTransportException[[chbsuv-naesdb02.it.actelion.com][10.180.148.45:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]; }
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:212)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:202)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:136)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]
    at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:212)
    at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:676)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:620)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
    at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    ... 3 more
Caused by:

QueryPhaseExecutionException[Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]
    at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:212)
    at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:676)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:620)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
    at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by damhau** [comment]
I've found out that I can workaroud this error message by changing the ES index settings max_result_window but the problem of getting only a few result when batch size is at 250 is still there.

**Comment by raghavendar-ts** [comment]
Hi

There was a bug in pagination part and I have fixed the same. I have also uploaded the updated version here https://github.com/raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report/releases/download/1.3/ElasticTab_v1.3.zip. Do you find this application useful? Do you have any recommendations to give?

Thank you

**Comment by damhau** [comment]
Hey, that s great news !!' I ll test it as soon as possible and let you know.

Thanks

**Comment by damhau** [comment]
dsfd

**Comment by damhau** [comment]
Hi,

I've tested and it's a bit better but I've another error now:

Setting Title and Headers
Building Excel Report
Processed 2000 of 75627
Processed 4000 of 75627
Processed 6000 of 75627
Processed 8000 of 75627
Processed 10000 of 75627
Processed 12000 of 75627
Processed 14000 of 75627
Processed 16000 of 75627
Processed 18000 of 75627
Processed 20000 of 75627
Processed 22000 of 75627
Processed 24000 of 75627
Processed 26000 of 75627
Processed 28000 of 75627
Processed 30000 of 75627
Processed 32000 of 75627
Processed 34000 of 75627
Processed 36000 of 75627
Processed 38000 of 75627
Processed 40000 of 75627
Processed 42000 of 75627
Processed 44000 of 75627
Processed 46000 of 75627
Processed 48000 of 75627
Processed 50000 of 75627
Processed 52000 of 75627
Processed 54000 of 75627
Processed 56000 of 75627
Processed 58000 of 75627
Processed 60000 of 75627
Processed 62000 of 75627
Processed 64000 of 75627
Sep 27, 2016 4:21:13 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.IllegalArgumentException: Invalid row number (65536) outside allowable range (0..65535)

**Comment by damhau** [comment]
Seems to be related to HSSF which support only excel 2003 that support only 65500 line.

It looks like the best would be to migrate from new HSSFWorkbook() with new XSSFWorkbook() ? Do that mean anything to you ?

http://stackoverflow.com/questions/10753562/invalid-row-number-65536-outside-allowable-range-0-65535

**Comment by raghavendar-ts** [comment]
I have changed the implementation to use XSSFWorkbook which has larger dataset support. GET API in Elasticsearch v2.2.1 (which I tested) is not supporting pagination for from:10000. I get the following error
**Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter**

I need to change the implementation to Scroll API to avoid this error. I will upload the updated version in week.

**Comment by damhau** [comment]
Great, do you have a version I can download with xsff ?

For the the result windows I changed the setting on the index as a workaround.

Thanks for your time !!!

**Comment by raghavendar-ts** [comment]
Hi

I have updated the code in ElasticTab v1.3.1 to use Scroll API and Excel (XSSF). Hopfully you should be able to use this version without any issues.

Thank you

**Comment by damhau** [comment]
Cool !!! Thank you very much !!!
