### ISSUE TITLE
Unable to load data into ElasticTab

### ISSUE THREAD

**Issue by Akhilesh-Anb** [raghavendar-ts/ElasticTab-Elasticsearch-to-Excel-Report#6]
I have changed properties as per my requirements.

when i start ElasticTab, its running fine but unable to get data into it.

> INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
> May 07, 2017 12:25:09 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
> SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
> NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{100.114.11.160}{100.114.11.160:9300}]]
>         at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
>

**Comment by Akhilesh-Anb** [comment]
Now i changed the elasticsearch.properties file as,

```
clustername=Dev
hostname=100.114.11.160:9200
```

Now i'm getting different error as,

> java.net.UnknownHostException: 100.114.117.169:9200: invalid IPv6 address
>         at java.net.InetAddress.getAllByName(InetAddress.java:1169)
>         at java.net.InetAddress.getAllByName(InetAddress.java:1126)
>         at java.net.InetAddress.getByName(InetAddress.java:1076)
>         at com.elastictab.report.ESReport.initializeESClient(ESReport.java:95)

**Comment by raghavendar-ts** [comment]
The hostname should be without the port number.

Change **hostname=100.114.11.160:9200** to **hostname=100.114.11.160**

**Comment by Akhilesh-Anb** [comment]
Hi Raghavendar,

First error i mentioned was without the port number. Can you please help me on this. It will help me a lot.

Thanks,
Akhilesh Appana

**Comment by raghavendar-ts** [comment]
Make sure you give the right cluster name in the property file.

**Comment by Akhilesh-Anb** [comment]
Yeah. I mentioned exactly in property file with my cluster name.  I have this problem

> INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
> May 07, 2017 12:25:09 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
> SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
> NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{100.114.11.160}{100.114.11.160:9300}]]
> at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)

**Comment by Akhilesh-Anb** [comment]
if you have a time please check your mail. I have sent you my link to connect with me. It will be great if you can help me for 10 min.

**Comment by alienjolka** [comment]
Hi! I have the same problem:

> SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{mn42JMTFS-O7c6zqXFSHBw}{192.168.0.1}{192.168.0.1:9300}]]

Please, help me

**Comment by raghavendar-ts** [comment]
I have made some changes and have uploaded it. Can you try downloading it again?
